[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
model = { path = "../model" }
planner = { path = "../planner" }
registry = { path = "../registry" }
resolver = { path = "../resolver" }

[lints]
workspace = true
