[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
executor = { path = "../executor" }
model = { path = "../model" }
planner = { path = "../planner" }
registry = { path = "../registry" }
resolver = { path = "../resolver" }
tempfile = "3"

[lints]
workspace = true
