[[bin]]
name = "daia"
path = "src/main.rs"

[package]
name = "cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
engine = { path = "../engine" }
model = { path = "../model" }
registry = { path = "../registry" }

[lints]
workspace = true
