############################################################
# DAIA Installation Directories
############################################################

readonly DAIA_HOME="/opt/daia"

readonly DAIA_CONFIG_DIR="${DAIA_HOME}/config"
readonly DAIA_LIB_DIR="${DAIA_HOME}/lib"
readonly DAIA_MODULE_DIR="${DAIA_HOME}/modules"
readonly DAIA_MANIFEST_DIR="${DAIA_HOME}/manifests"

############################################################
# DAIA State Directories
############################################################

readonly DAIA_STATE_DIR="/var/lib/daia"
readonly DAIA_LOG_DIR="/var/log"

readonly DAIA_FIRSTBOOT_LOG="${DAIA_LOG_DIR}/daia-firstboot.log"
readonly DAIA_FIRSTBOOT_STATE="${DAIA_STATE_DIR}/firstboot-complete"
readonly DAIA_SYSTEM_INFO="${DAIA_STATE_DIR}/system-info"
